services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: dearstyle
      POSTGRES_PASSWORD: dearstyle
      POSTGRES_DB: dearstyle
    ports:
      - "5432:5432"
    volumes:
      - dearstyle_pg18:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dearstyle -d dearstyle"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:8
    ports:
      - "6379:6379"
    volumes:
      - dearstyle_redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  dearstyle_pg18:
  dearstyle_redis:
